.TH (k)elogviewer 1 "May 29, 2013" "An elog viewer"

.SH NAME
(k)elogviewer \-\- a program to easily manage elog files created by Portage during emerge

.SH SYNOPSIS
.PP
.SY elogviewer
.OP \-p path
.
.SY kelogviewer 
.OP \-p path
.
.SY elogviewer
.B \-h
|
.B \-\-help

.SH DESCRIPTION
This document describes the
.B (k)elogviewer
program, a graphical frontend to list the elogs created during emerges of 
packages from 
.BR portage (5),
the package manager of Gentoo Linux.
.
The 
.B (k)elogviewer
program displays all warning and information messages generated during an installation
or an update of the programs using
.B portage
so that they can be reviewed at one glance. 

.SH USAGE
.TP
\fBelogviewer\fR, \fBkelogviewer\fR
invoking the program with 
.B elogviewer 
loads the Qt4 frontend.

.TP
.BI \-p\  path
.TQ
.BI \-\-elogpath\  path 
.
.B (k)elogviewer
reads the elogs in 
.I path 
instead of reading the current value for
.I path
in
.BR make.conf (5)
\.

.PP
To generate elogs, the user needs to tell Portage to activate the
saving features for the ELOG facilities in his /etc/make.conf file via
the line

.RS 4
PORTAGE_ELOG_SYSTEM="save"
.RE

and choose at least one out of

.RS 4
PORTAGE_ELOG_CLASSES="warn info error log"
.RE

Further prerequisite is the elog directory (in most cases
/var/log/portage/elog/, see variable PORT_LOGDIR), which may need to
be created and belong to the portage group. If the user wants to start
the program as non-root, he needs to add himself to portage group.
For more information on the ELOG system, see /etc/make.conf.example.

The program allows to select the ebuild functions in which to look for
messages, so unpack messages about patching can be disabled while
still having warnings from the post installation function without
informational messages.  elogs can be deleted individually or all in
one step.

.SH BUGS

.SH ENVIRONMENT

.SH SEE ALSO
/etc/make.conf.example

.SH AUTHOR
Mathias Laurin is the current maintainer of the program and wrote the
first gtk version from an idea by Timothy Kilbourn.  Jeremy
Wickersheimer wrote the first port to Qt3.  ML ported to Qt4.
Christian Faulhammer and ML wrote this man page.
 

